### PR TITLE
feature/426 inspec plugins junit2

### LINKED ISSUE #426: inspec junit reporter lost / junit2 reporter not available
Hi,

I'm able to create cli, html, json reports however junit* inspec reporter fail with inspec version 4.23.15, kitchen-terraform 5.5.0.

```
$$$$$$ Verifying the 'aws' system...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: ['junit' is not a valid reporter type.] on default-aws
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
...
...
...
...
...
...
$ bundle exec kitchen verify default
-----> Starting Test Kitchen (v2.7.2)
       test/fixtures/default/main.tf
-----> Verifying <default-aws>...
$$$$$$ Reading the Terraform input variables from the Kitchen instance state...
$$$$$$ Finished reading the Terraform input variables from the Kitchen instance state.
$$$$$$ Reading the Terraform output variables from the Kitchen instance state...
$$$$$$ Finished reading the Terraform output varibales from the Kitchen instance state.
$$$$$$ Verifying the systems...
$$$$$$ Verifying the 'aws' system...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: ['junit2' is not a valid reporter type.] on default-aws
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration


```

### PR DESCRIPTION
**Pull request by tbugfinder**
Based on the code of @tecracer-theinen within kitchen-inspec I'm trying to add this to kitchen-terraform.
I'd need some guidance though :-) on the attribute and executing the checks.

Running `bundle exec rake test:kitchen:all` fails as I don't have terragrunt darwin. Maybe PR pipeline will help.

Fixes #426

### CODE REVIEW

**Comment by tbugfinder** [comment]
Linux tests fail as those use test-kitchen 2.10 which introduce a change to the lifecycle hook function.

https://github.com/test-kitchen/test-kitchen/commit/5458a6dd90fb808e85c3d603ab1a9cd559ffc7ba

**Comment by tbugfinder** [comment]
hm, those tests which pass, might fail silently.....

Green - Windows Ruby 2.7:
```
Failures:

  1) Kitchen::Driver::Terraform#create when the action is a failure should raise an action failed error
     Failure/Error: lifecycle_hooks: ::Kitchen::LifecycleHooks.new(config),

     ArgumentError:
       wrong number of arguments (given 1, expected 2)
     # ./vendor/bundle/ruby/2.7.0/gems/test-kitchen-2.10.0/lib/kitchen/lifecycle_hooks.rb:34:in `initialize'
     # ./spec/lib/kitchen/driver/terraform_spec.rb:48:in `new'
     # ./spec/lib/kitchen/driver/terraform_spec.rb:48:in `block (2 levels) in <top (required)>'
     # ./spec/lib/kitchen/driver/terraform_spec.rb:117:in `block (3 levels) in <top (required)>'

```

**Comment by tbugfinder** [comment]
Hi @aaron-lane ,
IMHO the PR itself is ready for review. Those pipeline issues are a different story. Please let my know if there's anything I could do.

**Comment by aaron-lane** [comment]
Hey @tbugfinder! I agree it's not on you to solve the other test issues; I'll try to get those cleared up tonight. Regarding the plugin loading issue, is there a downside to always loading plugins? If it only improves support for more use cases, I'd say we should drop the options and do it unconditionally.

**Comment by tecracer-theinen** [comment]
Glad I could be of help in some way :+1: :grin:

**Comment by tbugfinder** [comment]
IMHO, loading inspec plugins increases startup time slightly. It shouldn't be an issue if inspec plugins are loaded always. It might rather increase user experience as e.g. junit2 just works.

I didn't check yet, which inspec version is required to load the plugins.

@tecracer-theinen Anything you could share why kitchen-inspec loads it conditionally?

**Comment by aaron-lane** [comment]
@tbugfinder if you rebase your branch, the unrelated test failures should be resolved 🎉 

I've opened https://github.com/newcontext-oss/kitchen-terraform/issues/437 to track the issue with Windows tests failing silently; thanks for pointing that out!

**Comment by tecracer-theinen** [comment]
> @tecracer-theinen Anything you could share why kitchen-inspec loads it conditionally?
That's easy: to allow backward compatibility.

Loading plugins was a new feature and had potential to change existing runtime behavior, dependent on plugins present. Given that it was unlikely to break anything in practice, I set the default to "true" but added this setting to turn it off in case of problems.

Execution speed was no factor for this.

**Comment by tbugfinder** [comment]
> @tbugfinder if you rebase your branch, the unrelated test failures should be resolved 🎉
> 
> I've opened #437 to track the issue with Windows tests failing silently; thanks for pointing that out!

Branch was rebased and conditional use reverted. Tests are not failing.

**Review by aaron-lane — APPROVED** [review]
Looks good!

**Comment by wyardley** [comment]
Thanks - do we know when this will be released?

**Comment by aaron-lane** [comment]
@wyardley let's say today 😁 https://github.com/newcontext-oss/kitchen-terraform/pull/438

**Comment by wyardley** [comment]
@aaron-lane thanks!

**Pull request merged**
