### PR TITLE
[WIP] Add for_each option to group config

### PR DESCRIPTION
**Pull request by RyanJarv**
Thinking this would be useful for reusing controls and avoiding doing the same thing there. Wanted to see if this is something that made sense before adding tests.

#### Changes
- Adds a for_each option to group config which allows you to specify a value to resolve then iterate on. A group is created for each iterated resolved value that has the key name merged with attributes.

  Example:
```
    verifier:
      groups:
        - name: group_name
          for_each:
            host: hosts
          controls:
            - generic_host
```

### CODE REVIEW

**Comment by RyanJarv** [comment]
This does pretty much the same thing as 'hostnames' but resolved key, values are added to attributes instead as used as hosts. Thinking this would be useful for other things but the specific case I had was checking hosts with awspec where the tests should run locally.

**Comment by RyanJarv** [comment]
It being a hash is just to specify a different key for the value being added to attributes. Not sure what the behavior should be when there is more then specified. Might make sense to have a hash of `attribute_key: something, lookup_value: <something>` instead.

**Comment by RyanJarv** [comment]
Thinking the way I did this is kinda hacky, just turned out to be the simplest way to implement it for now. Not sure if it makes sense to kinda copy what the hostname hash/attributes stuff does, it took me a bit to understand what was happening there but think I have a better idea of it now.

**Comment by aaron-lane** [comment]
@ryanjarv: could you achieve similar behaviour by iterating over a list attribute within the control?

**Comment by RyanJarv** [comment]
Yeah, that is mainly what I am avoiding with this but now that I think about it I'm not sure there's a good point. I got the idea that inspec profiles are meant to operate in one context at a time, but really that doesn't apply to awspec here since your operating in the context of the aws account not the host.

Anyways ignore me I'll go ahead and close this unless I remember any other reason I did this...

**Pull request closed without merging**
