### PR TITLE
WIP - Update example 0.12

### PR DESCRIPTION
**Pull request by errygg**
Updating the example to use 0.12 and getting an error running the `remote` tests:

```
√ extensive_kitchen_terraform % bundle exec kitchen verify                                                                                                                    (update_example_012)kitchen-terraform
-----> Starting Test Kitchen (v2.5.2)
-----> Verifying <extensive-suite-centos>...
$$$$$$ Reading the Terraform input variables from the Kitchen instance state...
$$$$$$ Finished reading the Terraform input variables from the Kitchen instance state.
$$$$$$ Reading the Terraform output variables from the Kitchen instance state...
$$$$$$ Finished reading the Terraform output varibales from the Kitchen instance state.
$$$$$$ Verifying the systems...
$$$$$$ Verifying the 'local' system...

Profile: Extensive Kitchen-Terraform (extensive_suite)
Version: 0.1.0
Target:  local://

  ✔  state_file: 0.12.26
     ✔  0.12.26 is expected to match /\d+\.\d+\.\d+/
  ✔  inspec_attributes: static terraform output
     ✔  static terraform output is expected to eq "static terraform output"
     ✔  static terraform output is expected to eq "static terraform output"


Profile Summary: 2 successful controls, 0 control failures, 0 controls skipped
Test Summary: 3 successful, 0 failures, 0 skipped
$$$$$$ Finished verifying the 'local' system.
$$$$$$ Verifying the 'remote' system...
>>>>>> no implicit conversion of Array into String
-----> Verifying <extensive-suite-ubuntu>...
$$$$$$ Reading the Terraform input variables from the Kitchen instance state...
$$$$$$ Finished reading the Terraform input variables from the Kitchen instance state.
$$$$$$ Reading the Terraform output variables from the Kitchen instance state...
$$$$$$ Finished reading the Terraform output varibales from the Kitchen instance state.
$$$$$$ Verifying the systems...
$$$$$$ Verifying the 'local' system...

Profile: Extensive Kitchen-Terraform (extensive_suite)
Version: 0.1.0
Target:  local://

  ✔  state_file: 0.12.26
     ✔  0.12.26 is expected to match /\d+\.\d+\.\d+/
  ✔  inspec_attributes: static terraform output
     ✔  static terraform output is expected to eq "static terraform output"
     ✔  static terraform output is expected to eq "static terraform output"


Profile Summary: 2 successful controls, 0 control failures, 0 controls skipped
Test Summary: 3 successful, 0 failures, 0 skipped
$$$$$$ Finished verifying the 'local' system.
$$$$$$ Verifying the 'remote' system...
>>>>>> no implicit conversion of Array into String
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 2 actions failed.
>>>>>>     Verify failed on instance <extensive-suite-centos>.  Please see .kitchen/logs/extensive-suite-centos.log for more details
>>>>>>     Verify failed on instance <extensive-suite-ubuntu>.  Please see .kitchen/logs/extensive-suite-ubuntu.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

### CODE REVIEW

**Comment by edwardbartholomew** [comment]
Greetings @errygg and thanks for updating this tutorial. I will clone your branch and attempt to reproduce/troubleshoot.

**Comment by edwardbartholomew** [comment]
When I ran a converge in v12, the output value remote_group_public_dns was a nested list and I found [below reference in v12 upgrade docs](https://www.terraform.io/upgrade-guides/0-12.html#referring-to-list-variables):
`In early versions of Terraform, before list support became first-class, we required using seemingly-redundant list brackets around a single expression in order to hint to the language interpreter that a list interpretation was desired`

Removing the brackets from the values for `remote_group_public_dns` in both outputs.tf and test/fixtures/wrappers/outputs.tf fixes the `no implicit conversion of Array into String` error when I converge and verify.

**Comment by aaron-lane** [comment]
Thanks for following up on this, @edwardbartholomew :partying_face:

**Comment by errygg** [comment]
Ah! Nice find @edwardbartholomew! I'll update and push up the changes.

**Pull request closed without merging**
