### PR TITLE
Add support for inspec 5 and drop inspec < 4.25.1

### LINKED ISSUE #479: Add Inspec 5.x support
I'm not sure if it's intentional, but is there a reason inspec 5.x isn't supported? Is there a plan for it to be at some point?

```
    kitchen-terraform (~> 6.1.0) was resolved to 6.1.0, which depends on
      inspec (>= 3, != 4.24.26, != 4.24.28, != 4.24.32, < 5)
```

### PR DESCRIPTION
**Pull request by wyardley**
Update dependencies to drop support for inspec versions below 4.25.1 

Update changelog

Also update inspec link in CONTRIBUTING.md

Fixes #479

### CODE REVIEW

**Comment by edwardbartholomew** [comment]
Thank you for your interest in kitchen-terraform and your effort adding support for Inspec 5. Per https://docs.chef.io/versions/ Inspec 3 is end of life so that is one argument in favor of us dropping support however it’s also the last “free distribution” as future releases fall under “commercial distribution” and requires accepting the license. I am not sure how that would effect all the users of this tool. Would love to read some discussion around this if relevant point.

**Comment by wyardley** [comment]
Thanks. I am personally in favor of dropping support for unsupported EOL versions, but what you say also makes sense.
If the maintainers would prefer to keep 3.x support in, it's not difficult to leave the constraint where it is.

**Comment by wyardley** [comment]
@aaron-lane any thoughts / preferences here?

**Comment by aaron-lane** [comment]
Sorry for the delay! If there isn't a technical blocker for maintaining support of InSpec 3 then I think we should do so for now to avoid the need for another major release.

**Comment by wyardley** [comment]
Looks like the failure is related to `junit2` not being a valid reporter type. I am successfully using `junit2` in inspec 4. Happy to adjust the test if it wasn't already breaking, though seems like [junit2 should still be a valid type](https://github.com/inspec/inspec/blob/main/lib/plugins/inspec-reporter-junit/README.md)?

**Comment by aaron-lane** [comment]
Thanks @wyardley. I just need to find some time to dig into this issue. I'm hoping by the end of the calendar week 🤞🏼

**Comment by wyardley** [comment]
Appreciate the research, and that makes sense. Let me know if the updated PR looks right to you.

**Comment by wyardley** [comment]
Also, lmk if you can handle everything related to it being a breaking change, or if you want me to add anything to the titles or update the labels or anything.

**Comment by aaron-lane** [comment]
> Also, lmk if you can handle everything related to it being a breaking change, or if you want me to add anything to the titles or update the labels or anything.

@wyardley all good; the change log update is sufficient!

**Comment by luckeyca** [comment]
Hi @aaron-lane, when will this merge be release? Thanks

**Comment by aaron-lane** [comment]
Hi @luckeyca 👋🏼 

Because this is a breaking change, I'm bundling it together with #299 for the next major version. I hope to have that finished in the next couple of weeks, but if you need this feature immediately, you can pin to the latest commit on the `master` branch as it should be stable for use.

**Comment by luckeyca** [comment]
Hi @aaron-lane, Thanks!

**Pull request merged**
